/**
 * Sync version from core/package.json to:
 * - core/moon.mod.json
 * - pages/src/content/docs/getting-started/cli.md (EN)
 * - pages/src/content/docs/ja/getting-started/cli.md (JA)
 */

const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const version = require(path.join(root, "package.json")).version;

// 1. Sync moon.mod.json
const moonModPath = path.join(root, "moon.mod.json");
const moonMod = JSON.parse(fs.readFileSync(moonModPath, "utf8"));
const oldMoonVersion = moonMod.version;
moonMod.version = version;
fs.writeFileSync(moonModPath, JSON.stringify(moonMod, null, "  ") + "\n", "utf8");
if (oldMoonVersion !== version) {
  console.log(`moon.mod.json: ${oldMoonVersion} -> ${version}`);
} else {
  console.log(`moon.mod.json: ${version} (no change)`);
}

// 2. Sync CLI docs
const docsFiles = [
  path.join(root, "..", "pages", "src", "content", "docs", "getting-started", "cli.md"),
  path.join(root, "..", "pages", "src", "content", "docs", "ja", "getting-started", "cli.md"),
];

const versionPattern = /\d+\.\d+\.\d+/g;

const replacements = [
  { pattern: /# purus v\d+\.\d+\.\d+/, replacement: `# purus v${version}` },
  { pattern: /Generated by Purus \d+\.\d+\.\d+/, replacement: `Generated by Purus ${version}` },
  { pattern: /\/\/ => "\d+\.\d+\.\d+"/, replacement: `// => "${version}"` },
];

for (const filePath of docsFiles) {
  if (!fs.existsSync(filePath)) {
    console.log(`Skipped (not found): ${path.relative(root, filePath)}`);
    continue;
  }

  let content = fs.readFileSync(filePath, "utf8");
  let changed = false;

  for (const { pattern, replacement } of replacements) {
    const newContent = content.replace(pattern, replacement);
    if (newContent !== content) {
      content = newContent;
      changed = true;
    }
  }

  if (changed) {
    fs.writeFileSync(filePath, content, "utf8");
    console.log(`Updated: ${path.relative(path.join(root, ".."), filePath)}`);
  } else {
    console.log(`No change: ${path.relative(path.join(root, ".."), filePath)}`);
  }
}

console.log(`\nAll versions synced to ${version}`);
